config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "donations#index"
  resources :report_news, only: [:index]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :donations, only: %i[new create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/community_event.rb
class CommunityEvent < ApplicationRecord
  belongs_to :user
end

app/models/donation.rb
class Donation < ApplicationRecord
  attr_accessor :amount_options
  AMOUNTS = [10, 20, 30, 40, 50, 60]
  TYPES = ["Catão de crédio - Mensal", "Cartão de crédito - Único", "Pix - Único"]

  belongs_to :user

end

app/models/report_new.rb
class ReportNew < ApplicationRecord
  belongs_to :user
  has_many :report_new_likes
end

app/models/report_new_like.rb
class ReportNewLike < ApplicationRecord
  belongs_to :user
  belongs_to :report_new
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable, :omniauthable

  has_many :community_events
  has_many :donations
  has_many :report_new_likes
  has_many :report_news
  has_many :user_depositions
end

app/models/user_deposition.rb
class UserDeposition < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
  before_action :authenticate_user!
end

app/controllers/donations_controller.rb
class DonationsController < ApplicationController
  before_action :donation_params, only: %i[create]

  def new
    @donation = Donation.new
  end

  def create
    @donation = Donation.new(donation_params)
    @donation.user = current_user
    @donation.amount = params[:donation][:amount_options].join.to_i if params[:donation][:amount].empty?

    if @donation.save
      redirect_to root_path, notice: "Obrigado pela sua doação"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def donation_params
    params.require(:donation).permit(:amount, :monthly, :payment_type)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/report_news_controller.rb
class ReportNewsController < ApplicationController
  def index
    @report_news = ReportNew.order(:created_at)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/donations/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Resumo da doação</h5>
            <%= link_to new_donation_path do %>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            <% end %>
          </div>
          <div class="modal-body">
            <h6 id="modal-amount">Valor:</h6>
            <h6 id="modal-type">Tipo:</h6>
          </div>
          <div class="modal-footer">
          <%= link_to new_donation_path do %>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Retornar</button>
          <% end %>
            <button type="button" class="btn">
              <%= f.submit class: "doar", label: "Doe já" %>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

app/views/donations/new.html.erb
<div class="container">
  <%= simple_form_for @donation do |f|  %>
    <%= f.input :amount_options,
                collection: Donation::AMOUNTS,
                as: :check_boxes,
                input_html: { class: "tag-selector" },
                item_wrapper_class: 'tag-item',
                label: "Escolha um valor" %>
    <%= f.input :amount,
                label: "Digite um valor"%>
    <%= f.input :payment_type,
                collection: Donation::TYPES,
                label: "Escolha um tipo de pagamento",
                id:"payment_type" %>
    <%= f.input :monthly,
                as: :boolean,
                label: "Gostaria de contribuir mensalmente?" %>

    <!-- Button trigger modal -->
    <button id="donation_button" type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      <p>Doe</p>
    </button>


    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Resumo da doação</h5>
            <%= link_to new_donation_path do %>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            <% end %>
          </div>
          <div class="modal-body">
            <h6 id="modal-amount">Valor:</h6>
            <h6 id="modal-type">Tipo:</h6>
          </div>
          <div class="modal-footer">
          <%= link_to new_donation_path do %>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Retornar</button>
          <% end %>
            <button type="button" class="btn">
              <%= f.submit class: "doar", label: "Doe já" %>
            </button>
          </div>
        </div>
      </div>
    </div>
  <% end %>

</div>

<script>
  document.getElementById("donation_button").addEventListener("click", myFunction);

  function myFunction() {
    const selected = document.querySelector(".tag-selector:checked")
    if (selected != null && selected.value != "") {
      document.getElementById("modal-amount").innerText = 'Valor: R$ ' + document.querySelector(".tag-selector:checked").value;
    } else {
      document.getElementById("modal-amount").innerText = 'Valor: R$ ' + document.getElementById("donation_amount").value;
    }
    document.getElementById("modal-type").innerText = 'Tipo: ' + document.getElementById("donation_payment_type").value;
  }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoleSolidario</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/report_news/index.html.slim
.row
  - @report_news.each do |report_new|
    .col-md-6  
      div.p-4.bg-white.w-75.mx-auto.my-4
        img.img-fluid src="https://media.istockphoto.com/photos/shot-of-a-handsome-young-man-standing-against-a-grey-background-picture-id1335941248?b=1&k=20&m=1335941248&s=170667a&w=0&h=sn_An6VRQBtK3BuHnG1w9UmhTzwTqM3xLnKcqLW-mzw="
        div.d-flex.mt-3
          i.h3.me-2.fa-regular.fa-heart
          h5 = report_new.report_new_likes.count + 12
          p.text-muted.flex-grow-1.text-end = "2" + (DateTime.now - report_new.created_at.to_date).to_i.to_s + " dias"
        p.fw-lighter = report_new.description

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>